CREATE PROCEDURE [dbo].[EchoParametersAsRowset]
    @i_bit as bit,
    @i_tinyint as tinyint,
    @i_smallint as smallint,
    @i_int as int,
    @i_bigint as bigint,
    @i_real as real,
    @i_float as float,
    @i_money as money,
    @i_decimal as decimal,
    @i_smalldatetime as smalldatetime,
    @i_date as date,
    @i_datetime as datetime,
    @i_datetimeoffset as datetimeoffset,
    @i_time as time,
    @i_nchar as nchar(4),
    @i_nvarchar as nvarchar(4),
    @i_binary as binary(4),
    @i_varbinary as varbinary(4),
    @i_uniqueidentifier as uniqueidentifier
AS
BEGIN
    SELECT @i_bit,
           @i_tinyint,
           @i_smallint,
           @i_int,
           @i_bigint,
           @i_real,
           @i_float,
           @i_money,
           @i_decimal,
           @i_smalldatetime,
           @i_date,
           @i_datetime,
           @i_datetimeoffset,
           @i_time,
           @i_nchar,
           @i_nvarchar,
           @i_binary,
           @i_varbinary,
           @i_uniqueidentifier
END
